name: agnostiko_scripts
description: Scripts utilitarios para facilitar el uso del SDKOne.
version: 2.1.01

environment:
  sdk: ^3.7.2

# Add regular dependencies here.
dependencies:
  path: ^1.9.1
  args: ^2.7.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.25.15
